source:
  name: source
  confluence_type: server
  site_url: ''
  home_path: ''
  space_key: ''
  root_page_id: ''
  include_label: ''
  exclude_ids:
  - ''
  fetch_pages_limit: ''
  fetch_attachments_limit: ''
  credentials:
    email: ''
    password: ''
    show_password: false
    mfa_enabled: false
    mfa_secret_key: ''
    api_token: ''
    rest_auth_type: header_auth
  label: ''
target:
  name: target
  confluence_type: Confluence Cloud
  site_url: ''
  home_path: ''
  space_key: ''
  root_page_id: ''
  include_label: ''
  exclude_ids: []
  fetch_pages_limit: ''
  fetch_attachments_limit: ''
  credentials:
    email: ''
    password: ''
    show_password: false
    mfa_enabled: false
    mfa_secret_key: ''
    api_token: ''
    rest_auth_type: basic_auth
