name: Build App for Linux

on:
  workflow_dispatch: 
  push:
  pull_request:
    branches: [ master ]
  release:
    types: [published, prereleased]


jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.10

      - name: Install Tkinter for Ubuntu
        run: sudo apt-get install python3-tk

      - name: Install virtual envs and dependencies
        run: |
          python3 -m pip3 install --upgrade pipenv wheel

      - id: cache-pipenv
        uses: actions/cache@v4
        with:
          path: ~/.local/share/virtualenvs
          key: ${{ runner.os }}${{ runner.os }}-pipenv-${{ hashFiles('**/Pipfile.lock') }}

      - name: Install pipenv dependencies
        if: steps.cache-pipenv.outputs.cache-hit != 'true'
        run: |
          pipenv install --deploy --dev

      - name: Build Linux executable
        run: |
          pipenv run pyinstaller --hidden-import=tkinter --name="spaces_tool_linux" --splash splash.png --onefile main.py

      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            dist/spaces_tool_linux

