name: Build App for Windows

on:
  workflow_dispatch: 
  pull_request:
    branches: [ master ]
  release:
    types: [published, prereleased]


jobs:
  build:
    runs-on: windows-latest
    timeout-minutes: 10

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.10

      - name: Install virtual environment
        run: |
          python3 -m pip install --upgrade pipenv wheel

      - id: cache-pipenv
        uses: actions/cache@v4
        with:
          path: ~/.local/share/virtualenvs
          key: ${{ runner.os }}${{ runner.os }}-pipenv-${{ hashFiles('**/Pipfile.lock') }}

      - name: Install dependencies
        if: steps.cache-pipenv.outputs.cache-hit != 'true'
        run: |
          pipenv install --deploy --dev

      - name: Create binary release for the app
        run: |
          pipenv run pyinstaller --icon=icon.ico --windowed --name="spaces_tool" --splash splash.png --onefile main.py

      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            dist/spaces_tool_windows.exe

